### PR TITLE
Add variable with json data to App.

### PR DESCRIPTION
**Pull request by ViddeM**

### CODE REVIEW

**Review by PontusLindblom — DISMISSED** [review]

**Review by ejohnsson6 — DISMISSED** [review]

**Review by ericlp — CHANGES_REQUESTED** [review]
Plz fix which file it is in

**Review by ghost — CHANGES_REQUESTED** [review]
Break out stuff from App.tsx

**Review by ghost — APPROVED** [review]

**Review by PontusLindblom — APPROVED** [review]
Ser helt ok ut //Vidde

**Review by ericlp — APPROVED** [review]
:crab:

**Review by teifalsadi — APPROVED** [review]
Bra jobbat Vidde! Du får mitt godkännande!

**Pull request merged**
