### PR TITLE
Added tslint to travis

### PR DESCRIPTION
**Pull request by ejohnsson6**

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ViddeM** [comment]
This should probably not be merged before the Sprint 1 PRs are merged so that they can (finally) be merged and not be delayed further.

**Comment by ghost** [comment]
> This should probably not be merged before the Sprint 1 PRs are merged so that they can (finally) be merged and not be delayed further.

I might be wrong, but the result would be that styling would need to be fixed from this branch instead from the feature branches that would introduce breaking styling. That seems counterintuitive, and while I would like to get all of this done today we need more active individuals anyway.

**Comment by ejohnsson6** [comment]
> > This should probably not be merged before the Sprint 1 PRs are merged so that they can (finally) be merged and not be delayed further.
> 
> I might be wrong, but the result would be that styling would need to be fixed from this branch instead from the feature branches that would introduce breaking styling. That seems counterintuitive, and while I would like to get all of this done today we need more active individuals anyway.

Alternatively we could just make sure that the current PRs don't have any tslint warnings.

**Review by ericlp — APPROVED** [review]

**Comment by PontusLindblom** [comment]
Test fails at: **ERROR: /home/travis/build/dat256-weedle/weedle/app/parkit/types/ParkingSpots.tsx:4:16 - Don't use 'Number' as a type. Avoid using the `Number` type. Did you mean `number`?**

**Pull request closed without merging**
