### PR TITLE
Team reflection w2

### PR DESCRIPTION
**Pull request by ViddeM**

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Nej jag vägrar

**Review by PontusLindblom — CHANGES_REQUESTED** [review]
1. Put the text through a spell checking program. There are a lot of spelling errors.
2. Is this really a team reflection for week 2? If not, rename the document to "W3.md".

**Comment by ViddeM** [comment]
@Praxzy Fixed :), considering the length of the text and my stress level when writing it, there wasn't THAT many spelling errors ;)

**Review by PontusLindblom — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by PontusLindblom** [comment]
Sorry @midona-rhel, jag råkade be dig om en review igen!

**Review by ejohnsson6 — APPROVED** [review]

**Pull request merged**
