### PR TITLE
Resolve #55 and Resolve #69

### LINKED ISSUE #55: Fix folder structure
As a developer I want there to be a folder structure that follows the groups criteria. This to make it easier to find files.

**Task breakdown**
- [x] Make sure that the folder structures follow that which is stated in the social contract.

**Success criteria** 
Same as tasks.

### LINKED ISSUE #69: Add tslint to travis
As a developer I want travis to check tslint.

**Task breakdown**
- [ ] Travis checks tslint.
- [ ] Fix all current files.

__success criteria same as tasks__

### PR DESCRIPTION
**Pull request by ghost**
This merge will fix tslint and folder structure

### CODE REVIEW

**Comment by ghost** [comment]
The folder structure issue will be moved manually since I can't connect two issues to one pull request

**Review by ejohnsson6 — DISMISSED** [review]

**Review by ericlp — COMMENTED** [review]
Logoloader.tsx is in the root directory. Shouldn't we create a utils folder or something of that kind for helper functions?

**Review by ericlp — COMMENTED** [review]
And while you are moving files maybe you could delete the duplicate prettierrc, There seems to be two files as of now.
 * .prettierrc
 *  prettierrc

The latter one should be removed.

**Comment by ghost** [comment]
> And while you are moving files maybe you could delete the duplicate prettierrc, There seems to be two files as of now.
> 
> * .prettierrc
> * prettierrc
> 
> The latter one should be removed.



> Logoloader.tsx is in the root directory. Shouldn't we create a utils folder or something of that kind for helper functions?

Fixed both issues

**Review by ericlp — APPROVED** [review]
yes i like

**Review by ejohnsson6 — APPROVED** [review]

**Review by PontusLindblom — APPROVED** [review]

**Pull request merged**
